### ISSUE TITLE
Creat a simple react program calculator 

### ISSUE THREAD

**Issue by Iamsamgeorge** [Iamsamgeorge/Wedoreact#1]

**Comment by YashM211** [comment]
Can you assign this to me

**Comment by iamdiinesh** [comment]
Hellow @Iamsamgeorge ,i will resolve the issue can you assign to me

**Comment by Iamsamgeorge** [comment]
> Hellow @Iamsamgeorge ,i will resolve the issue can you assign to me

Assigning to you.

**Comment by AdityaPrasad275** [comment]
Hey @Iamsamgeorge can you assign me this issue.

**Comment by AdityaPrasad275** [comment]
Hey @Iamsamgeorge !, i have made a simple app for this and opened a pull request regarding the same. Please do review it

**Comment by Iamsamgeorge** [comment]
merged
