### ISSUE TITLE
Create simple python program to find the sum of 5 numbers.

### ISSUE THREAD

**Issue by Iamsamgeorge** [Iamsamgeorge/Wedoreact#2]

**Comment by iamdiinesh** [comment]
Hello @Iamsamgeorge ,i will resolve the issue can you assign to me

**Comment by Iamsamgeorge** [comment]
> Hello @Iamsamgeorge ,i will resolve the issue can you assign to me

Assigning to you @iamdiinesh

**Comment by iamdiinesh** [comment]
done with the problem

**Comment by Iamsamgeorge** [comment]
Thanks @iamdiinesh  good work
