### ISSUE TITLE
Create simple python program to find the multiplication of 5 numbers

### ISSUE THREAD

**Issue by Iamsamgeorge** [Iamsamgeorge/Wedoreact#3]

**Comment by iamdiinesh** [comment]
Hello @Iamsamgeorge ,i will resolve the issue can you assign to me

**Comment by Iamsamgeorge** [comment]
> Hello @Iamsamgeorge ,i will resolve the issue can you assign to me

Assigning to you @iamdiinesh

**Comment by iamdiinesh** [comment]
the issue has been resolved to the path: Python/Multiply_5_numbers.py

**Comment by Iamsamgeorge** [comment]
closing the issue.
