### ISSUE TITLE
Create simple python program to find the sum of array.

### ISSUE THREAD

**Issue by Iamsamgeorge** [Iamsamgeorge/Wedoreact#4]

**Comment by iamdiinesh** [comment]
Hello @Iamsamgeorge ,i will resolve the issue can you assign to me

**Comment by Iamsamgeorge** [comment]
> Hello @Iamsamgeorge ,i will resolve the issue can you assign to me

Assigning to you @iamdiinesh

**Comment by uditi1002** [comment]
can i be assigned to this please?

**Comment by iamdiinesh** [comment]
> can i be assigned to this please?

@uditi1002 stay updated on this repo more issue on it way.

**Comment by iamdiinesh** [comment]
The issue has been resolved

**Comment by Iamsamgeorge** [comment]
Good work @iamdiinesh
